$LOAD_PATH << './lib'
require 'rake'
require 'pathname'

src="lib"
testdir="spec"

Gem::Specification.new do |s|
  s.name = "rakedotnet"
  s.files = FileList["#{src}/**/*.rb",
                     "#{testdir}/**/*.rb"]
  src_path = Pathname.new src
  source_lib_path = FileList["#{src}/**/*.rb"]
  .uniq
  .map { |f| relative_to_lib = Pathname.new(f).relative_path_from(src_path)
  relative_to_lib.to_s.chomp(File.extname(relative_to_lib)) }
  File.open "#{src}/rakedotnet.rb", 'w' do |f|
    f << "# Generated by .gemspec on #{DateTime.now}\n"
    source_lib_path.each { |p| f << "require '#{p}'\n" }
  end
  s.test_files = FileList["#{testdir}/**/*.rb"]
  s.version = ENV['version_number'] || '1.0.0'
  s.summary = "Rake tasks for building .NET projects"
  s.description = "Provides MSBuild, NUnit, BCP, SqlCmd, MsTest, MinifyJS, jstest tasks for Rake build files"
  s.has_rdoc = true
  s.license = 'BSD'
  s.homepage = "https://github.com/wied03/Rake.NET"
  s.rdoc_options << '--inline-source' << '--line-numbers'
  s.author = "Brady Wied"
  s.email = "brady@bswtechconsulting.com"
  s.add_runtime_dependency('windows-pr')
  s.add_dependency('bsw_dnet_install_util', '1.1.5')
  s.add_development_dependency 'rspec'
end
