source 'https://rubygems.org'
source 'http://weez.weez.wied.us:9292'
gem 'rspec'
gem 'ci_reporter'
gem 'rake'
gem 'geminabox'
gem 'bsw_dnet_install_util', '1.1.3'
gem 'win32stub', '1.0.1', :git => 'git://github.com/wied03/Win32TestStub.git'
