# .NET has the various settings stuff going on (app settings you can manually include and access via Configuration.AppSettings
# and also the autogenerated .settings files.

# using .net adapters, the .settings file will be necessary.

# with a web project, regardless of what's in the backend projects, ultimately when it's running, it's the settings hanging off
# the web project that will be used

# nonetheless on a development machine, it's good to keep the .settings files that end up with DB connection strings in them
# out of version control and instead version templates.  then, using the actual developer's DB connection string, create
# those files so they can work with the DB in Visual Studio